import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport:'viewport-fit=cover',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='p-2 mx-6 bg-black text-white'>
        <div>
        <Header>
        {children}</Header>
        <Footer/>
        </div>
        </div></body>
    </html>
  )
}
